platform :ios, '13.0'
use_frameworks!

target 'TFInvest' do
  pod 'Base', :path => '../Frameworks/Base/'
  pod 'Services', :path => '../Frameworks/Services/'
  pod 'Authorization', :path => '../Frameworks/Authorization/'
  pod 'Core', :path => '../Frameworks/Core/'
  pod 'R.swift'
  pod 'SwiftLint'
  # Pods for TFInvest

end
