platform :ios, '13.0'
use_frameworks!


pre_install do |installer|
    installer.pod_targets.flat_map do |pod_target|
        if pod_target.pod_target_srcroot.include? 'Frameworks'
            pod_target_srcroot = pod_target.pod_target_srcroot
            pod_target_path = pod_target_srcroot.sub('${PODS_ROOT}/..', '.')
            pod_target_sources_path = pod_target_path + '/' + pod_target.name + '/Classes'
            generated_file_path = pod_target_sources_path + '/R.generated.swift'
            File.new(generated_file_path, 'w')
        end
    end
end

target 'TFInvest' do
  pod 'R.swift'
  pod 'SwiftLint'
  pod 'Kingfisher/SwiftUI'
  pod 'Base', :path => 'Frameworks/Base/'
  pod 'Services', :path => 'Frameworks/Services/'
  pod 'Authorization', :path => 'Frameworks/Authorization/'
  pod 'Core', :path => 'Frameworks/Core/'
  pod 'Assembly', :path => 'Frameworks/Assembly/'
  pod 'Stock', :path => 'Frameworks/Stock/'
  pod 'News', :path => 'Frameworks/News/'
  # Pods for TFInvest

end
